[project]
name = "download-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Danil Saydakov", email = "saydakov09@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.31.0",
    "dotenv>=0.9.9",
    "yt-dlp>=2026.8.19",
]

[project.scripts]
download-bot = "download_bot:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
